FROM python:3.5.1

RUN mkdir /code
WORKDIR /code

RUN apt-get update \
    && apt-get install -y build-essential \
                          libffi-dev \
                          libssl-dev \
                          libxml2-dev \
                          libxslt1-dev \
COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/

CMD ["py.test"]
