FROM metabrainz/python:3.8-20201201

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN mkdir /code
WORKDIR /code

# Python dependencies
RUN apt-get update \
     && apt-get install -y --no-install-recommends \
                        build-essential \
                        ca-certificates \
                        cron \
                        git \
                        libpq-dev \
                        libffi-dev \
                        libssl-dev \
                        libxml2-dev \
                        libxslt1-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip==21.0.1

COPY requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /code/

# Compile translations
RUN pybabel compile -d critiquebrainz/frontend/translations

CMD dockerize -wait tcp://db_test:5432 -timeout 60s \
    dockerize -wait tcp://musicbrainz_db:5432 -timeout 600s \
    python manage.py init_db --test-db \
    && py.test --junitxml=reports/tests.xml
